# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ VANS-1711 ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment : PROD
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g .
      - run: vansah-connect -c ${{vars.VANSAH_TOKEN}}
      - run: vansah-connect -f ./testng-report.xml
      - run: vansah-connect -t "PVT-C500" -s "failed" -a "PVT-4"

